### ISSUE TITLE
Add roles for users

### ISSUE THREAD

**Issue by AndrewEgorov** [qakit/tcms#3]
E.g.:

* QA role: 
  * can add test cases to system. By default they are not approved
  * can assign test plan to himself and start plan execution
  * can edit test cases 
* Test Manager role: 
  * this user can approve test cases. Only this role has ability change IsApproved field
  * can add projects/versions
  * create test plans
  * can manage users and assign roles (e.g. specify Project/Manager (if necessary etc...)

**Comment by OlegZee** [comment]
Plan to implement roles + permissions. User or role is granted some permissions. Being assigned a particular role user "inherits" role permissions.

Permission list:
- common permissions
  - add test-cases - allows to add/edit own test-cases
  - edit test-cases - allows to edit all test-cases, not only own
  - assign test-plan to himself
  - plan execution - allows to start/stop plan execution, set execution status

- test managerial
  - approve test-cases
  - create test-plans - allows to create/edit test plans
  - assign test-plan

- administrative privileges
  - manage products - allows to CRUD products, versions and components
  - manage users - create/validate/delete accounts, manage user roles

**Comment by OlegZee** [comment]
Implemented roles, permissions and permission checking policies
